name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build examples
      run: cargo build --verbose --examples
    - name: Run tests
      run: cargo test --verbose
    - name: Test minimal feature combinations
      run: |
        cargo test --workspace --no-default-features --locked
        for features in std tracing std,tracing clap clap,tracing clap,dotenv subcommands std,subcommands; do
          cargo test --workspace --no-default-features --features "$features" --locked
        done
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build examples
      run: cargo build --verbose --examples
    - name: Run tests
      run: cargo test --verbose
